GET http://localhost:8080/api/users
Accept: application/json

###
###
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "name": "Vova",
  "password": "123"
}

###
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "name": "Vova",
  "password": "123",
  "role": "admin"
}

POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "name": "Ivan",
  "password": "1234"
}

###
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "name": "Ivan",
  "password": "123",
  "role": "student"
}

###
GET http://localhost:8080/
Accept: application/json

###

